#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=sheybani@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=30
#SBATCH --mem-per-cpu 8G
#SBATCH --time=0-1:00:00
#SBATCH --partition=gpu
#SBATCH --gpus 1
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --job-name=jobsim
#SBATCH --output=jobsim_Out
#SBATCH --error=jobsim_Err

######  Module commands #####



######  Job commands go below this line #####
embedding_root="/N/project/infant_image_statistics/preproc_saber/embeddings/gist/"
save_dir="/N/project/infant_image_statistics/preproc_saber/frame_similarity/"
chunk_min=30
#metric='cosine'

python ~/github/PretrainingInfantEgocentric/dataanalysis/compute_frame_similarity.py -embedding_root $embedding_root -save_dir $save_dir --chunk_min $chunk_min

#python ~/github/PretrainingInfantEgocentric/dataanalysis/plot_similarity.py
