#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=sheybani@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=80
#SBATCH --time=0-8:00:00
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --job-name=job_c5encode
#SBATCH --output=job_c5encode_Out
#SBATCH --error=job_c5encode_Err

######  Module commands #####



######  Job commands go below this line #####

#embedder_name="CLIP-ViT-H-14-laion2B" => use slurm_clip instead

#save_dir="/N/scratch/sheybani/homeview_embeddings/"
save_dir="/N/project/infant_image_statistics/preproc_saber/embeddings/"

jpg_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps/"
#jpg_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps_adult/"
ds_rate=1


#'003MT' '004AB' '005JL_withrotation' '006AP_withrotation' '010BF_withrotation' '015JM' '017EW_withrotation' '019JC' '020EC' '020MS_withlighting' '022JL' '023NF' '024AM' '024RZ' '025TT' '028CK' '031HW' '034NW' '036MR_withrotation' '037SM_withrotation' '038RB' '039ED' '040ER_withrotation' '041EC'  '042MB_withrotation' '043MP' '047MS' '053MT')

#subj_dirs="004AB+005JL_withrotation+006AP_withrotation+010BF_withrotation"
subj_dirs="042MB_withrotation+043MP+047MS+053MT"
echo $subj_dirs

#for GIST
#python ~/github/PretrainingInfantEgocentric/preproc/encode_images_gist.py -save_dir $save_dir --jpg_root $jpg_root --subj_dirs $subj_dirs --ds_rate $ds_rate

#for CLIP
#python ~/github/PretrainingInfantEgocentric/preproc/encode_clip_mp_sharedmemory.py -embedder_name $embedder_name -save_dir $save_dir --jpg_root $jpg_root --subj_dirs $subj_dirs --ds_rate $ds_rate

