#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=sheybani@iu.edu
#SBATCH -A r00117
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=40
#SBATCH --time=0-2:00:00
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --job-name=job_rae0
#SBATCH --output=job_rae0_Out
#SBATCH --error=job_rae0_Err


save_path='/N/slate/sheybani/tmp_dir/trainedmodels/slowness_ae/rae0_h16_v025.pt'

#g0: 008MS+009SS_withrotation+010BF_withrotation+011EA_withrotation+012TT_withrotation+013LS+014SN+015JM+016TF+017EW_withrotation
#g1: 026AR+027SS+028CK+028MR+029TT+030FD+031HW+032SR+033SE+034JC_withlighting
#g2: 043MP+044ET+046TE+047MS+048KG+049JC+050AB+050AK_rotation+051DW

#g0: 008MS+009SS+010BF+011EA+012TT+013LS+014SN+015JM+016TF+017EW
#g2: 043MP+044ET+046TE+047MS+048KG+049JC+050AB+050AK+051DW

subj_dirs='008MS+009SS+010BF+011EA+012TT+013LS+014SN+015JM+016TF+017EW'

jpg_root='/N/project/infant_image_statistics/preproc_saber/JPG_10fps/'
'/N/project/infant_image_statistics/video_frames/'
#'/N/project/infant_image_statistics/preproc_saber/JPG_10fps/'


objective='r'
image_size=64
crop_size=8
seq_len=6
hidden_size=16
num_epochs=10
ds_rate=6


######  Job commands go below this line #####
python ~/github/baby-vision-curriculum/shallow/autoencoder_rnn_positive.py -jpg_root $jpg_root -subj_dirs $subj_dirs -save_path $save_path -objective $objective --image_size $image_size --crop_size $crop_size --hidden_size $hidden_size --num_epochs $num_epochs --ds_rate $ds_rate

#python ~/github/baby-vision-curriculum/shallow/autoencoder_rnn.py -jpg_root $jpg_root -subj_dirs $subj_dirs -save_path $save_path -objective $objective --image_size $image_size --crop_size $crop_size --hidden_size $hidden_size --num_epochs $num_epochs