#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=sheybani@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=80
#SBATCH --time=0-12:00:00
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --job-name=job_gcluster
#SBATCH --output=job_gcluster_Out
#SBATCH --error=job_gcluster_Err

######  Module commands #####

#for embedding stuff
embedder_name='gist'

## Choose the root
#embedding_root="/N/project/infant_image_statistics/preproc_saber/embeddings/CLIP-ViT-H-14-laion2B/"
embedding_root="/N/project/infant_image_statistics/preproc_saber/embeddings/gist/"

#pixel level analyses
#embedding_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps/"
#embedding_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps_adult/"


## choose the save directory
#distance_per_frame
#save_dir="/N/project/infant_image_statistics/preproc_saber/distance_per_frame/CLIP-ViT-H-14-laion2B/"

#oneDprojection
#save_dir="/N/project/infant_image_statistics/preproc_saber/oneDprojections/CLIP-ViT-H-14-laion2B/"

#oneDprojection1min10fps
#save_dir="/N/project/infant_image_statistics/preproc_saber/oneDprojections1min10fps/CLIP-ViT-H-14-laion2B/"

#distance_matrix
#save_dir="/N/project/infant_image_statistics/preproc_saber/similarity_matrix_film/pixel/"

#clusters
save_dir="/N/project/infant_image_statistics/preproc_saber/clusters/gist/"


## Choose the subjects to be processed

#subj_dirs='003MT+004AB+005JL_withrotation+006AP_withrotation+010BF_withrotation+015JM+017EW_withrotation+019JC+020EC+020MS_withlighting+022JL+023NF+024AM+024RZ+025TT+028CK+031HW+034NW+036MR_withrotation+037SM_withrotation+038RB+039ED+040ER_withrotation+041EC++042MB_withrotation+043MP+047MS+053MT'

subj_dirs='all'

norm_factor=1
image_size=224
chunk_min=30

dim=1
method='tsne'

ds_rate=10


######  Job commands go below this line #####
#python ~/github/PretrainingInfantEgocentric/dataanalysis/compute_distance_pixel_per_frame_v2.py -embedding_root $embedding_root -norm_factor $norm_factor -save_dir $save_dir --image_size $image_size --chunk_min $chunk_min --subj_dirs $subj_dirs

#python ~/github/PretrainingInfantEgocentric/dataanalysis/compute_distance_embedding_per_frame_v2.py -embedder_name $embedder_name -embedding_root $embedding_root -norm_factor $norm_factor -save_dir $save_dir --subj_dirs $subj_dirs 

#python ~/github/PretrainingInfantEgocentric/dataanalysis/compute_projection.py -embedding_root $embedding_root -save_dir $save_dir --subj_dirs $subj_dirs --dim $dim --method $method --ds_rate $ds_rate --chunk_min $chunk_min

#python ~/github/PretrainingInfantEgocentric/dataanalysis/compute_distance_matrix.py -embedding_root $embedding_root -save_dir $save_dir --subj_dirs $subj_dirs --ds_rate $ds_rate --chunk_min $chunk_min

#python ~/github/PretrainingInfantEgocentric/dataanalysis/compute_distance_matrix_pixel.py -embedding_root $embedding_root -save_dir $save_dir --subj_dirs $subj_dirs --ds_rate $ds_rate --chunk_min $chunk_min

python ~/github/PretrainingInfantEgocentric/dataanalysis/compute_embedding_clusters.py -embedder_name $embedder_name -embedding_root $embedding_root -save_dir $save_dir --subj_dirs $subj_dirs --ds_rate $ds_rate --chunk_min $chunk_min
