#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=sheybani@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=30
#SBATCH --time=0-8:00:00
#SBATCH --mem-per-cpu 8G
#SBATCH --partition=gpu
#SBATCH --gpus 4
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --job-name=jobtall
#SBATCH --output=jobtall_Out
#SBATCH --error=jobtall_Err

######  Module commands #####



######  Job commands go below this line #####
n_epochs=30
model_dir="/N/scratch/sheybani/trainedmodels/multistage/simclr/aug26/"
ds_task="toybox"

# candidate checkpoints
model_fname1="model_012_stage_2_seed_0_687.pt"
model_fname2="model_012_stage_2_seed_0_912.pt"
model_fname3="model_012_stage_2_seed_1_103.pt"
model_fname4="model_012_stage_2_seed_1_281.pt"
model_fname5="model_012_stage_2_seed_2_145.pt"
model_fname6="model_012_stage_2_seed_2_9.pt"

model_fname7="model_222_stage_2_seed_0_182.pt"
model_fname8="model_222_stage_2_seed_0_727.pt"
model_fname9="model_222_stage_2_seed_1_650.pt"
model_fname10="model_222_stage_2_seed_1_901.pt"
model_fname11="model_222_stage_2_seed_2_352.pt"
model_fname12="model_222_stage_2_seed_2_596.pt"

model_fname13="model_210_stage_2_seed_0_257.pt"
model_fname14="model_210_stage_2_seed_0_72.pt"
model_fname15="model_210_stage_2_seed_1_182.pt"
model_fname16="model_210_stage_2_seed_1_749.pt"
model_fname17="model_210_stage_2_seed_2_771.pt"
model_fname18="model_210_stage_2_seed_2_994.pt"


# StringArray=($model_fname1 $model_fname2 $model_fname3 $model_fname4 $model_fname5 $model_fname6)
# StringArray=($model_fname7 $model_fname8 $model_fname9 $model_fname10 $model_fname11 $model_fname12)

declare -a StringArray=($model_fname1 $model_fname2 $model_fname3 $model_fname4 $model_fname5 $model_fname6 $model_fname7 $model_fname8 $model_fname9 $model_fname10 $model_fname11 $model_fname12 $model_fname13 $model_fname14 $model_fname15 $model_fname16 $model_fname17 $model_fname18)
# Iterate the string array using for loop
for model_fname in ${StringArray[@]}; do
   echo $model_fname
   model_fpath=$model_dir$model_fname
   python ~/github/PretrainingInfantEgocentric/downstream/downstream_wrapper_ddp.py --task=$ds_task --model_path=$model_fpath --outdir=$model_dir --epochs=$n_epochs
done