#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=sheybani@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=30
#SBATCH --time=0-8:00:00
#SBATCH --mem-per-cpu 8G
#SBATCH --partition=gpu
#SBATCH --gpus 4
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --job-name=job_encode_vit
#SBATCH --output=job_encode_vit_Out
#SBATCH --error=job_encode_vit_Err

######  Module commands #####



######  Job commands go below this line #####

embedder_name="CLIP-ViT-H-14-laion2B"

"tf_efficientnet_b7_ns"
#"tf_efficientnet_l2_ns"
#"resnetv2_101x1_bitm"
#"vit_large_patch16_224_in21k"
#"vit_b_16"
#"vit_l_32"
#"resnet50"

save_dir="/N/project/infant_image_statistics/preproc_saber/embeddings/"
jpg_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps/"

#jpg_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps_adult/"
#image_size=224

ds_rate=1

#pretrained='n'
#SEED=$(($RANDOM%1000))

#pretrained='y'
SEED=0

subj_dirs="all"
echo $subj_dirs
#remove_head='y'
batch_size=16

python ~/github/PretrainingInfantEgocentric/preproc/encode_images_clip.py -embedder_name $embedder_name -save_dir $save_dir --jpg_root $jpg_root --subj_dirs $subj_dirs --ds_rate $ds_rate --seed $SEED --batch_size $batch_size

#--pretrained $pretrained  --remove_head $remove_head 



#python ~/github/PretrainingInfantEgocentric/preproc/encode_images_ddp_v4.py -embedder_name $embedder_name -save_dir $save_dir --jpg_root $jpg_root --subj_dirs $subj_dirs --image_size $image_size --ds_rate $ds_rate --pretrained $pretrained --seed $SEED

