#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=sheybani@iu.edu
#SBATCH -A r00117
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=80
#SBATCH --time=0-12:00:00
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --job-name=job_pg0
#SBATCH --output=job_pg0_Out
#SBATCH --error=job_pg0_Err


module load deeplearning/2.9.1

jpg_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps/"

image_size=224
crop_size=32
ds_rate=1

#g0='008MS+009SS_withrotation+010BF_withrotation+011EA_withrotation+012TT_withrotation+013LS+014SN+015JM+016TF+017EW_withrotation'
#g0='008MS+009SS+010BF+011EA+012TT+013LS+014SN+015JM+016TF+017EW'
# g1='026AR+027SS+028CK+028MR+029TT+030FD+031HW+032SR+033SE+034JC_withlighting'
#g2='043MP+044ET+046TE+047MS+048KG+049JC+050AB+050AK_rotation+051DW'
#g2='043MP+044ET+046TE+047MS+048KG+049JC+050AB+050AK+051DW'

save_dir="/N/project/infant_image_statistics/preproc_saber/rf_analysis/gspatch_32p224_10fps/g0/"
subj_dirs="008MS+009SS_withrotation+010BF_withrotation+011EA_withrotation+012TT_withrotation+013LS+014SN+015JM+016TF+017EW_withrotation"

python /N/project/baby_vision_curriculum/github/baby-vision-curriculum/shallow/extract_patch.py -save_dir $save_dir --jpg_root $jpg_root --subj_dirs $subj_dirs --ds_rate $ds_rate --image_size $image_size --crop_size $crop_size