#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=sheybani@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=40
#SBATCH --mem=58G
#SBATCH --time=2-00:00:00
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --job-name=job2_encode_clip
#SBATCH --output=job2_encode_clip_Out
#SBATCH --error=job2_encode_clip_Err

######  Module commands #####



######  Job commands go below this line #####

embedder_name="CLIP-ViT-H-14-laion2B"

#save_dir="/N/scratch/sheybani/homeview_embeddings/"
save_dir="/N/project/infant_image_statistics/preproc_saber/embeddings/"
#jpg_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps_adult/"
jpg_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps/"
ds_rate=1

batch_size=128
num_workers=40

#subj_dirs="all"

#declare -a StringArray=('007OW' '008MS' '009SS_withrotation' '011EA_withrotation' '012TT_withrotation' '013LS' '014SN' '016TF' '018MT' '026AR' '027SS' '028MR' '029TT' '030FD' '032SR' '033SE' '034JC_withlighting' '034MT' '044ET' '045NA' '046TE' '048KG' '049JC'  '050AB' '050AK_rotation' '051DW' '053KD')

declare -a StringArray=('051DW' '053KD')

# Iterate the string array using for loop
for subj_name in ${StringArray[@]}; do
   echo $subj_name
   srun python ~/github/PretrainingInfantEgocentric/preproc/encode_images_clip.py -embedder_name $embedder_name -save_dir $save_dir --jpg_root $jpg_root --subj_dirs $subj_name --ds_rate $ds_rate --batch_size $batch_size --num_workers $num_workers &
done
wait
