#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=sheybani@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=80
#SBATCH --time=0-09:00:00
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --job-name=jobgist
#SBATCH --output=jobgist_Out
#SBATCH --error=jobgist_Err

######  Module commands #####

save_dir="/N/project/infant_image_statistics/preproc_saber/embeddings/"
jpg_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps_adult/"
#jpg_root="/N/project/infant_image_statistics/preproc_saber/JPG_10fps/"
image_size=224
nblocks=4
subj_dirs='all'



######  Job commands go below this line #####
python ~/github/PretrainingInfantEgocentric/preproc/encode_images_gist.py -save_dir $save_dir --jpg_root $jpg_root --image_size $image_size --nblocks $nblocks --subj_dirs $subj_dirs

#embedding_root="/N/project/infant_image_statistics/preproc_saber/embeddings/gist/"
#save_dir="/N/project/infant_image_statistics/preproc_saber/frame_similarity/"
chunk_min=30

#python ~/github/PretrainingInfantEgocentric/dataanalysis/compute_frame_similarity.py -embedding_root $embedding_root -save_dir $save_dir --chunk_min $chunk_min


